"""
Milvus Vector Database Service
Handles embedding storage and similarity search
"""
from typing import List, Tuple, Optional
from uuid import UUID
from fastapi import HTTPException
from app.config.milvus import get_collection
from app.config.settings import settings


class MilvusService:
    """Service for Milvus operations"""
    
    def __init__(self):
        self.collection_name = settings.MILVUS_COLLECTION_NAME
    
    def insert_embedding(
        self,
        case_id: str,
        image_embedding: List[float],
        text_embedding: List[float]
    ) -> bool:
        """
        Insert case embeddings into Milvus
        
        Args:
            case_id: Case UUID as string
            image_embedding: Image embedding vector from MedSigLip
            text_embedding: Text embedding vector from MedSigLip
        
        Returns:
            True if successful
        
        Note:
            Image and text embeddings are generated by MedSigLip model
            Call the embedding service to generate these vectors before inserting
        """
        try:
            collection = get_collection()
            collection.load()
            
            entities = [
                [case_id],  # case_id
                [image_embedding],  # image_embedding
                [text_embedding]  # text_embedding
            ]
            
            collection.insert(entities)
            collection.flush()
            
            return True
        
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to insert embedding: {str(e)}")
    
    def search_similar_by_image(
        self,
        image_embedding: List[float],
        top_k: int = 5
    ) -> Tuple[List[str], List[float]]:
        """
        Search for similar cases by image embedding
        
        Args:
            image_embedding: Query image embedding vector
            top_k: Number of similar cases to return
        
        Returns:
            Tuple of (case_ids, similarity_scores)
        """
        try:
            collection = get_collection()
            collection.load()
            
            search_params = {
                "metric_type": "L2",
                "params": {"nprobe": 10}
            }
            
            results = collection.search(
                data=[image_embedding],
                anns_field="image_embedding",
                param=search_params,
                limit=top_k,
                output_fields=["case_id"]
            )
            
            if not results or len(results[0]) == 0:
                return [], []
            
            case_ids = [hit.entity.get('case_id') for hit in results[0]]
            scores = [hit.distance for hit in results[0]]
            
            return case_ids, scores
        
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to search similar cases: {str(e)}")
    
    def search_similar_by_text(
        self,
        text_embedding: List[float],
        top_k: int = 5
    ) -> Tuple[List[str], List[float]]:
        """
        Search for similar cases by text embedding
        
        Args:
            text_embedding: Query text embedding vector
            top_k: Number of similar cases to return
        
        Returns:
            Tuple of (case_ids, similarity_scores)
        """
        try:
            collection = get_collection()
            collection.load()
            
            search_params = {
                "metric_type": "L2",
                "params": {"nprobe": 10}
            }
            
            results = collection.search(
                data=[text_embedding],
                anns_field="text_embedding",
                param=search_params,
                limit=top_k,
                output_fields=["case_id"]
            )
            
            if not results or len(results[0]) == 0:
                return [], []
            
            case_ids = [hit.entity.get('case_id') for hit in results[0]]
            scores = [hit.distance for hit in results[0]]
            
            return case_ids, scores
        
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to search similar cases: {str(e)}")
    
    def delete_embedding(self, case_id: str) -> bool:
        """
        Delete embedding by case_id
        
        Args:
            case_id: Case UUID as string
        
        Returns:
            True if successful
        """
        try:
            collection = get_collection()
            collection.load()
            
            expr = f'case_id == "{case_id}"'
            collection.delete(expr)
            collection.flush()
            
            return True
        
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to delete embedding: {str(e)}")
    
    def get_embedding(self, case_id: str) -> Optional[dict]:
        """
        Retrieve embedding by case_id
        
        Args:
            case_id: Case UUID as string
        
        Returns:
            Dictionary with image and text embeddings
        """
        try:
            collection = get_collection()
            collection.load()
            
            expr = f'case_id == "{case_id}"'
            results = collection.query(
                expr=expr,
                output_fields=["case_id", "image_embedding", "text_embedding"]
            )
            
            if not results:
                return None
            
            return results[0]
        
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to get embedding: {str(e)}")


# Create singleton instance
milvus_service = MilvusService()
