export const patientsData = [
  {
    id: 1,
    name: "Nguyễn Văn An",
    age: 45,
    gender: "Nam",
    diagnosis: "Lao phổi",
    findings: "Đông đặc phổi",
    admissionDate: "2025-11-05",
    status: "Under Treatment",
    image: "/src/mock_data/patient_data/01_Tuberculosis/origin.png",
    bloodType: "O+",
    lastVisit: "2025-11-10",
  },
  {
    id: 2,
    name: "Trần Thị Bình",
    age: 32,
    gender: "Nữ",
    diagnosis: "Lao phổi",
    findings: "Tổn thương phổi",
    admissionDate: "2025-11-03",
    status: "Stable",
    image: "/src/mock_data/patient_data/01_Tuberculosis/origin.png",
    bloodType: "A+",
    lastVisit: "2025-11-09",
  },
  {
    id: 3,
    name: "Lê Văn Cường",
    age: 58,
    gender: "Nam",
    diagnosis: "Viêm phổi",
    findings: "Phình động mạch chủ",
    admissionDate: "2025-11-01",
    status: "Critical",
    image: "/src/mock_data/patient_data/02_pneumonia/origin.png",
    bloodType: "B+",
    lastVisit: "2025-11-11",
  },
  {
    id: 4,
    name: "Phạm Thị Dung",
    age: 28,
    gender: "Nữ",
    diagnosis: "Viêm phổi",
    findings: "Tim to",
    admissionDate: "2025-11-07",
    status: "Admitted",
    image: "/src/mock_data/patient_data/02_pneumonia/origin.png",
    bloodType: "AB+",
    lastVisit: "2025-11-08",
  },
  {
    id: 5,
    name: "Hoàng Văn Em",
    age: 63,
    gender: "Nam",
    diagnosis: "Viêm phổi",
    findings: "Thâm nhiễm phổi",
    admissionDate: "2025-10-28",
    status: "Under Treatment",
    image: "/src/mock_data/patient_data/02_pneumonia/origin.png",
    bloodType: "O-",
    lastVisit: "2025-11-10",
  },
  {
    id: 6,
    name: "Vũ Thị Phương",
    age: 41,
    gender: "Nữ",
    diagnosis: "Viêm phổi",
    findings: "Tổn thương phổi",
    admissionDate: "2025-11-02",
    status: "Stable",
    image: "/src/mock_data/patient_data/02_pneumonia/origin.png",
    bloodType: "A-",
    lastVisit: "2025-11-09",
  },
  {
    id: 7,
    name: "Đặng Văn Giang",
    age: 52,
    gender: "Nam",
    diagnosis: "Bệnh phổi khác",
    findings: "Tổn thương phổi",
    admissionDate: "2025-10-25",
    status: "Admitted",
    image: "/src/mock_data/patient_data/03_Otherdisease/origin.png",
    bloodType: "B-",
    lastVisit: "2025-11-11",
  },
  {
    id: 8,
    name: "Bùi Thị Hoa",
    age: 36,
    gender: "Nữ",
    diagnosis: "Bệnh phổi khác",
    findings: "Dày màng phổi",
    admissionDate: "2025-11-06",
    status: "Stable",
    image: "/src/mock_data/patient_data/03_Otherdisease/origin.png",
    bloodType: "O+",
    lastVisit: "2025-11-08",
  },
  {
    id: 9,
    name: "Ngô Văn Inh",
    age: 47,
    gender: "Nam",
    diagnosis: "Bệnh phổi khác",
    findings: "Xơ phổi",
    admissionDate: "2025-11-04",
    status: "Under Treatment",
    image: "/src/mock_data/patient_data/03_Otherdisease/origin.png",
    bloodType: "A+",
    lastVisit: "2025-11-10",
  },
  {
    id: 10,
    name: "Đinh Thị Kim",
    age: 55,
    gender: "Nữ",
    diagnosis: "Lao phổi",
    findings: "Vôi hóa",
    admissionDate: "2025-10-30",
    status: "Stable",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "B+",
    lastVisit: "2025-11-09",
  },
  {
    id: 11,
    name: "Phan Văn Long",
    age: 39,
    gender: "Nam",
    diagnosis: "Lao phổi",
    findings: "Khối u phổi",
    admissionDate: "2025-11-08",
    status: "Critical",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "AB-",
    lastVisit: "2025-11-11",
  },
  {
    id: 12,
    name: "Trương Thị Mai",
    age: 44,
    gender: "Nữ",
    diagnosis: "Lao phổi",
    findings: "Dày màng phổi",
    admissionDate: "2025-11-05",
    status: "Stable",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "O+",
    lastVisit: "2025-11-10",
  },
  {
    id: 13,
    name: "Lý Văn Nam",
    age: 61,
    gender: "Nam",
    diagnosis: "Lao phổi",
    findings: "Xơ phổi",
    admissionDate: "2025-10-20",
    status: "Under Treatment",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "A+",
    lastVisit: "2025-11-11",
  },
  {
    id: 14,
    name: "Dương Thị Oanh",
    age: 33,
    gender: "Nữ",
    diagnosis: "Viêm phổi",
    findings: "Tim to",
    admissionDate: "2025-11-09",
    status: "Admitted",
    image: "/src/mock_data/patient_data/05_pneumonia/origin.png",
    bloodType: "B+",
    lastVisit: "2025-11-10",
  },
  {
    id: 15,
    name: "Võ Văn Phúc",
    age: 50,
    gender: "Nam",
    diagnosis: "Viêm phổi",
    findings: "Phình động mạch chủ",
    admissionDate: "2025-10-26",
    status: "Critical",
    image: "/src/mock_data/patient_data/06_pneumonia/origin.png",
    bloodType: "O-",
    lastVisit: "2025-11-11",
  },
  {
    id: 16,
    name: "Cao Thị Quỳnh",
    age: 42,
    gender: "Nữ",
    diagnosis: "Viêm phổi",
    findings: "Tim to",
    admissionDate: "2025-10-22",
    status: "Admitted",
    image: "/src/mock_data/patient_data/06_pneumonia/origin.png",
    bloodType: "A-",
    lastVisit: "2025-11-09",
  },
  {
    id: 17,
    name: "Mai Văn Sơn",
    age: 37,
    gender: "Nam",
    diagnosis: "Không có phát hiện bất thường",
    findings: "Phổi bình thường",
    admissionDate: "2025-11-07",
    status: "Stable",
    image: "/src/mock_data/patient_data/07_Nofinding/origin.png",
    bloodType: "B-",
    lastVisit: "2025-11-10",
  },
  {
    id: 18,
    name: "Tạ Thị Thanh",
    age: 48,
    gender: "Nữ",
    diagnosis: "Lao phổi",
    findings: "Đông đặc phổi",
    admissionDate: "2025-10-29",
    status: "Under Treatment",
    image: "/src/mock_data/patient_data/01_Tuberculosis/origin.png",
    bloodType: "AB+",
    lastVisit: "2025-11-11",
  },
  {
    id: 19,
    name: "Lương Văn Tuấn",
    age: 56,
    gender: "Nam",
    diagnosis: "Viêm phổi",
    findings: "Thâm nhiễm phổi",
    admissionDate: "2025-10-27",
    status: "Critical",
    image: "/src/mock_data/patient_data/02_pneumonia/origin.png",
    bloodType: "O+",
    lastVisit: "2025-11-10",
  },
  {
    id: 20,
    name: "Trịnh Thị Uyên",
    age: 35,
    gender: "Nữ",
    diagnosis: "Bệnh phổi khác",
    findings: "Xơ phổi",
    admissionDate: "2025-11-06",
    status: "Stable",
    image: "/src/mock_data/patient_data/03_Otherdisease/origin.png",
    bloodType: "A+",
    lastVisit: "2025-11-09",
  },
  {
    id: 21,
    name: "Đoàn Văn Việt",
    age: 49,
    gender: "Nam",
    diagnosis: "Lao phổi",
    findings: "Vôi hóa",
    admissionDate: "2025-10-24",
    status: "Critical",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "B+",
    lastVisit: "2025-11-11",
  },
  {
    id: 22,
    name: "Từ Thị Xuân",
    age: 38,
    gender: "Nữ",
    diagnosis: "Viêm phổi",
    findings: "Tim to",
    admissionDate: "2025-11-08",
    status: "Admitted",
    image: "/src/mock_data/patient_data/05_pneumonia/origin.png",
    bloodType: "O-",
    lastVisit: "2025-11-10",
  },
  {
    id: 23,
    name: "Chu Văn Yên",
    age: 60,
    gender: "Nam",
    diagnosis: "Lao phổi",
    findings: "Khối u phổi",
    admissionDate: "2025-10-21",
    status: "Under Treatment",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "A-",
    lastVisit: "2025-11-11",
  },
  {
    id: 24,
    name: "Lâm Thị Hà",
    age: 43,
    gender: "Nữ",
    diagnosis: "Bệnh phổi khác",
    findings: "Dày màng phổi",
    admissionDate: "2025-11-04",
    status: "Stable",
    image: "/src/mock_data/patient_data/03_Otherdisease/origin.png",
    bloodType: "B-",
    lastVisit: "2025-11-09",
  },
  {
    id: 25,
    name: "Kiều Văn Anh",
    age: 53,
    gender: "Nam",
    diagnosis: "Lao phổi",
    findings: "Xơ phổi",
    admissionDate: "2025-11-09",
    status: "Admitted",
    image: "/src/mock_data/patient_data/04_Turbeculosis/origin.png",
    bloodType: "AB+",
    lastVisit: "2025-11-11",
  },
];
