export const patientsData = [
  {
    id: 1,
    name: "John Smith",
    age: 45,
    gender: "Male",
    diagnosis: "Type 2 Diabetes",
    admissionDate: "2025-11-05",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    bloodType: "O+",
    lastVisit: "2025-11-10",
  },
  {
    id: 2,
    name: "Emma Johnson",
    age: 32,
    gender: "Female",
    diagnosis: "Hypertension",
    admissionDate: "2025-11-03",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    bloodType: "A+",
    lastVisit: "2025-11-09",
  },
  {
    id: 3,
    name: "Michael Brown",
    age: 58,
    gender: "Male",
    diagnosis: "Coronary Artery Disease",
    admissionDate: "2025-11-01",
    status: "Critical",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    bloodType: "B+",
    lastVisit: "2025-11-11",
  },
  {
    id: 4,
    name: "Sarah Davis",
    age: 28,
    gender: "Female",
    diagnosis: "Asthma",
    admissionDate: "2025-11-07",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    bloodType: "AB+",
    lastVisit: "2025-11-08",
  },
  {
    id: 5,
    name: "James Wilson",
    age: 63,
    gender: "Male",
    diagnosis: "Chronic Kidney Disease",
    admissionDate: "2025-10-28",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    bloodType: "O-",
    lastVisit: "2025-11-10",
  },
  {
    id: 6,
    name: "Jennifer Martinez",
    age: 41,
    gender: "Female",
    diagnosis: "Rheumatoid Arthritis",
    admissionDate: "2025-11-02",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    bloodType: "A-",
    lastVisit: "2025-11-09",
  },
  {
    id: 7,
    name: "Robert Taylor",
    age: 52,
    gender: "Male",
    diagnosis: "Lung Cancer",
    admissionDate: "2025-10-25",
    status: "Critical",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    bloodType: "B-",
    lastVisit: "2025-11-11",
  },
  {
    id: 8,
    name: "Lisa Anderson",
    age: 36,
    gender: "Female",
    diagnosis: "Migraine",
    admissionDate: "2025-11-06",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    bloodType: "O+",
    lastVisit: "2025-11-08",
  },
  {
    id: 9,
    name: "David Thomas",
    age: 47,
    gender: "Male",
    diagnosis: "Gastroesophageal Reflux",
    admissionDate: "2025-11-04",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    bloodType: "A+",
    lastVisit: "2025-11-10",
  },
  {
    id: 10,
    name: "Mary Jackson",
    age: 55,
    gender: "Female",
    diagnosis: "Osteoporosis",
    admissionDate: "2025-10-30",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    bloodType: "B+",
    lastVisit: "2025-11-09",
  },
  {
    id: 11,
    name: "William White",
    age: 39,
    gender: "Male",
    diagnosis: "Depression",
    admissionDate: "2025-11-08",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    bloodType: "AB-",
    lastVisit: "2025-11-11",
  },
  {
    id: 12,
    name: "Patricia Harris",
    age: 44,
    gender: "Female",
    diagnosis: "Thyroid Disorder",
    admissionDate: "2025-11-05",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    bloodType: "O+",
    lastVisit: "2025-11-10",
  },
  {
    id: 13,
    name: "Christopher Martin",
    age: 61,
    gender: "Male",
    diagnosis: "Stroke Recovery",
    admissionDate: "2025-10-20",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    bloodType: "A+",
    lastVisit: "2025-11-11",
  },
  {
    id: 14,
    name: "Linda Thompson",
    age: 33,
    gender: "Female",
    diagnosis: "Anxiety Disorder",
    admissionDate: "2025-11-09",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    bloodType: "B+",
    lastVisit: "2025-11-10",
  },
  {
    id: 15,
    name: "Daniel Garcia",
    age: 50,
    gender: "Male",
    diagnosis: "Liver Cirrhosis",
    admissionDate: "2025-10-26",
    status: "Critical",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    bloodType: "O-",
    lastVisit: "2025-11-11",
  },
  {
    id: 16,
    name: "Barbara Martinez",
    age: 42,
    gender: "Female",
    diagnosis: "Breast Cancer",
    admissionDate: "2025-10-22",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    bloodType: "A-",
    lastVisit: "2025-11-09",
  },
  {
    id: 17,
    name: "Matthew Robinson",
    age: 37,
    gender: "Male",
    diagnosis: "Sleep Apnea",
    admissionDate: "2025-11-07",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    bloodType: "B-",
    lastVisit: "2025-11-10",
  },
  {
    id: 18,
    name: "Susan Clark",
    age: 48,
    gender: "Female",
    diagnosis: "Multiple Sclerosis",
    admissionDate: "2025-10-29",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    bloodType: "AB+",
    lastVisit: "2025-11-11",
  },
  {
    id: 19,
    name: "Joseph Rodriguez",
    age: 56,
    gender: "Male",
    diagnosis: "Parkinson's Disease",
    admissionDate: "2025-10-27",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    bloodType: "O+",
    lastVisit: "2025-11-10",
  },
  {
    id: 20,
    name: "Karen Lewis",
    age: 35,
    gender: "Female",
    diagnosis: "Fibromyalgia",
    admissionDate: "2025-11-06",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    bloodType: "A+",
    lastVisit: "2025-11-09",
  },
  {
    id: 21,
    name: "Thomas Lee",
    age: 49,
    gender: "Male",
    diagnosis: "Heart Failure",
    admissionDate: "2025-10-24",
    status: "Critical",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    bloodType: "B+",
    lastVisit: "2025-11-11",
  },
  {
    id: 22,
    name: "Nancy Walker",
    age: 38,
    gender: "Female",
    diagnosis: "Celiac Disease",
    admissionDate: "2025-11-08",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    bloodType: "O-",
    lastVisit: "2025-11-10",
  },
  {
    id: 23,
    name: "Charles Hall",
    age: 60,
    gender: "Male",
    diagnosis: "Prostate Cancer",
    admissionDate: "2025-10-21",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
    bloodType: "A-",
    lastVisit: "2025-11-11",
  },
  {
    id: 24,
    name: "Betty Allen",
    age: 43,
    gender: "Female",
    diagnosis: "Lupus",
    admissionDate: "2025-11-04",
    status: "Stable",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
    bloodType: "B-",
    lastVisit: "2025-11-09",
  },
  {
    id: 25,
    name: "Paul Young",
    age: 53,
    gender: "Male",
    diagnosis: "Pneumonia",
    admissionDate: "2025-11-09",
    status: "Under Treatment",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    bloodType: "AB+",
    lastVisit: "2025-11-11",
  },
];
